"""add student_can_recharge to wallet

Revision ID: 8f5879b3d253
Revises: 003b7332db87
Create Date: 2026-03-05 21:11:31.515362

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8f5879b3d253'
down_revision = '003b7332db87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet_category_restrictions')
    op.drop_table('wallet_product_restrictions')
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_can_recharge', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_column('student_can_recharge')

    op.create_table('wallet_product_restrictions',
    sa.Column('wallet_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('wallet_product_restrictions_product_id_fkey')),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], name=op.f('wallet_product_restrictions_wallet_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('wallet_product_restrictions_pkey'))
    )
    op.create_table('wallet_category_restrictions',
    sa.Column('wallet_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('wallet_category_restrictions_category_id_fkey')),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], name=op.f('wallet_category_restrictions_wallet_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('wallet_category_restrictions_pkey'))
    )
    # ### end Alembic commands ###
