"""add parent_id to user proper

Revision ID: a9360a502e8a
Revises: f9ba2a9b681d
Create Date: 2026-03-10 00:59:45.561962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9360a502e8a'
down_revision = 'f9ba2a9b681d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['parent_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
