"""add product price logs

Revision ID: b0b84e56de24
Revises: de07d0e17646
Create Date: 2026-03-05 19:07:27.216546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0b84e56de24'
down_revision = 'de07d0e17646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_price_logs',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('old_cost_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('new_cost_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('old_sell_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('new_sell_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_price_logs')
    # ### end Alembic commands ###
