"""add student_can_recharge

Revision ID: f9ba2a9b681d
Revises: 3d47ce2cc314
Create Date: 2026-03-10 00:51:14.981964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9ba2a9b681d'
down_revision = '3d47ce2cc314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_can_recharge', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_column('student_can_recharge')

    # ### end Alembic commands ###
